[package]
name = "saju"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
chrono = { version = "0.4.38", features = ["std"] }
chrono-tz = "0.10.0"
